export const strings = {
  welcome: {
    title: 'Welcome to MindSparkle',
    subtitle: 'Upload documents, get great summaries, and chat with AI.',
  },
  home: {
    title: 'MindSparkle',
    getStarted: 'Get Started',
    description: 'AI-powered learning platform',
  },
  upload: {
    title: 'Learning Documents',
    uploadButton: 'Upload Document',
    selectFile: 'Select a file to upload',
    supportedFormats: 'Supported formats: PDF, DOCX, PPTX, TXT',
    noDocuments: 'No documents uploaded yet',
  },
  actions: {
    summarize: 'Summarize',
    study: 'Plan',
    generateVideo: 'Generate Video',
    test: 'Test',
    labs: 'Labs',
  },
  sidebar: {
    exams: 'Exams',
    interviewTests: 'Interview Tests',
    summarization: 'Summarization',
    aiVideo: 'AI Video',
    performance: 'Performance',
    labs: 'Labs',
    settings: 'Settings',
  },
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success!',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
  },
};
